### ISSUE TITLE
Customize bodyParser options?

### ISSUE THREAD

**Issue by joncursi** [apollographql/meteor-integration#102]
I'm hitting some json byte size limits and came to the conclusion that I need to bump up the bodyParser `limit` option. However, it doesn't look like there is a current way to specify custom [bodyParser options](https://www.npmjs.com/package/body-parser#bodyparserjsonoptions). Is there a way to do this?

**Comment by xavcz** [comment]
Hey @joncursi, thanks for opening an issue about that!

You can do some stuff on the server [with that option](https://github.com/apollographql/meteor-integration/blob/master/src/main-server.js#L62-L63), else no there is no way to do this at the moment.

Would you mind open a PR to make it possible? 💯

**Comment by smeijer** [comment]
I'm also hitting the `request entity too large` error. This config is seriously needed.

**Comment by dobesv** [comment]
Hi, actually you can do this already:

```
const config = {
  configServer: expressServer => {
    expressServer.use(bodyParser.json({ limit: '10mb' }));
  },
};

createApolloServer(options, config);

```

This `bodyParser` will be used instead of the one created by this package.  This works because the body parser writes a flag into the request indicating that it was already parsed, then the one added later by this package checks that flag and skips parsing the body.
