### ISSUE TITLE
Support Apollo 2.0

### ISSUE THREAD

**Issue by dburles** [apollographql/meteor-integration#109]
Looks like there's API changes in version 2.0 that are incompatible with the latest version of this package.

**Comment by xavcz** [comment]
Hey @dburles!

Yes it's not compatible at the moment! Meanwhile a PR is opened, here is how to make the graphql express server created by this package working with Apollo Client 2.0:

```js
import { ApolloClient } from 'apollo-client';
import { ApolloLink } from 'apollo-link';
import { HttpLink } from 'apollo-http-link';
import { InMemoryCache } from 'apollo-cache-inmemory';

// replaces createNetworkInterface
const httpLink = new HttpLink({ uri: Meteor.absoluteUrl('graphql') });

// replaces networkInterface.use([{ applyMiddleware .... 
const authLink = new ApolloLink((operation, forward) => {
  const token = Accounts._storedLoginToken(); // from local storage
  
  operation.setContext(() => ({
    headers: {
      'meteor-login-token': token,
    },
  }));
  
  return forward(operation);
});

const cache = new InMemoryCache();

const client = new ApolloClient({
  link: authLink.concat(httpLink),
  cache,
});
```

I believe it would be a great time to make this package less "black box": only the authLink would be exported by this package (and this package should become a NPM package?), so the configuration of the client is handled by the developer and not by a black box.

**Comment by dburles** [comment]
Thanks @xavcz! that sounds great. If the client component can be removed without requiring writing too much boilerplate on the developers side I'm all for it.

**Comment by csillag** [comment]
As far as I can tell, Apollo Client 2.0 is now out of beta.
So, isn't it time to update this package,too?

**Comment by vbelolapotkov** [comment]
@xavcz I guess there is a typo above:

`import { HttpLink } from 'apollo-http-link';`

must be 

`import { HttpLink } from 'apollo-link-http';`

**Comment by xavcz** [comment]
Yeah sure. Want to take a shot at making a Meteor Accounts / Apollo integration compatible with Apollo Client 2.0?

**Comment by csillag** [comment]
No, I kind of just expect this to work out of the box, since these components are all advertised as "ready for production" and such.

If this is not the case, it would be great to clarify this in the relevant README files.

**Comment by jaredtmartin** [comment]
Thanks a lot, this just saved me.  Just to be clear here's the code that works using vbelolapotkov's correction:

```
import { ApolloClient } from 'apollo-client';
import { ApolloLink } from 'apollo-link';
import { HttpLink } from 'apollo-http-link';
import { InMemoryCache } from 'apollo-cache-inmemory';

// replaces createNetworkInterface
const httpLink = new HttpLink({ uri: Meteor.absoluteUrl('graphql') });

// replaces networkInterface.use([{ applyMiddleware .... 
const authLink = new ApolloLink((operation, forward) => {
  const token = Accounts._storedLoginToken(); // from local storage
  
  operation.setContext(() => ({
    headers: {
      'meteor-login-token': token,
    },
  }));
  
  return forward(operation);
});

const cache = new InMemoryCache();

const client = new ApolloClient({
  link: authLink.concat(httpLink),
  cache,
});
```

**Comment by dobesv** [comment]
How do I adapt this to work with graphql subscriptions?

**Comment by jamiter** [comment]
@dobesv, an easy way to use subscriptions right now with Meteor is by using ddp-apollo: https://github.com/Swydo/ddp-apollo

It works with Apollo Client 2 and there is an option to only use it for subscriptions: https://github.com/Swydo/ddp-apollo#using-ddp-only-for-subscriptions

@xavcz Are there plans to make this package work with subscriptions? An option would be to merge the subscription handling part from ddp-apollo into this package and it would work out-of-the-box. Any thoughts? Might want to discuss that in another ticket though 😄

**Comment by xavcz** [comment]
Waoooow!! `DDPLink` & `DDPSubscriptionLink`, dude you are killing it! 👏 

So far my opinion has been, quoting myself from previous comment:
> I believe it would be a great time to make this package less "black box": only the authLink would be exported by this package (**and this package should become a NPM package?**), so the configuration of the client is handled by the developer and not by a black box.

Let's recap what this `apollo` package is doing at the moment:
1. making GraphQL aware of the Meteor current user from client to server.
2. configure Apollo Client & Apollo Server Express in one line of code. 

I love the `1.`, I find it to be the real interest.

However, I can't stand `2.`: it feels to me like before when we were wrapping Node packages in Atmosphere packages and doesn't help people to understand what they are doing with Apollo.

It looks like you, people involved in this thread, would like to keep the value `2.`. May I not be the right person anymore to maintain this package?

➡️ I'd love to help for and review any pull request to make this package evolve in the direction the community would like it to go, and transfer the maintainer role.

**Comment by jamiter** [comment]
Thanks for the quick reply and kind words @xavcz!

I think you are right about `1` and for people wanting the most basic integration between Apollo and Meteor a `meteorAuthLink` and maybe a `getUserForContext(req)` for express would be more than enough.

But you don't need an official `apollo` package for that... Those are 2 npm packages, like you mentioned. And going forward I would really like those 2 packages to exist, so developers like yourself can use those and apply your GraphQL/Apollo knowledge to it's full extend for your own setup.

The question is, what do people expect when they type `meteor add apollo`? To setup an express server from scratch? That's not really Meteor-ish... That's just plain old node 😄  On the forums you see the question now and then when Meteor will offer a more integrated solution. I think we can offer that, but leave the door open for people to go the *do-it-yourself* route. 

> it feels to me like before when we were wrapping Node packages in Atmosphere packages and doesn't help people to understand what they are doing with Apollo.

Yeah, that's true. But what is it they need to know about how the data is loaded? Maybe that's something for "later". That has been the Meteor spirit from the start. *(I'm not necessarily promoting this attitude, but I'm trying to understand a beginners perspective)*

DDP-Apollo is also partly a black box, but to be honest, most of it was simply available in Meteor. So no wrapping of node-modules. Just make use of DDP. Setting up an express server for someone else feels a lot more dirty then a single Meteor method and publication. 🤔 

I'm a bit on the fence here. People should have the possibility to customize everything and use/learn all the default Apollo setup there is. But a Meteor `apollo` package should do more then just offer 2 npm packages and let the rest up to the user.

So in my opinion we create the 2 npm packages. And this package either dissolves, or it gives a more integrated solution. What kind of integrations? Possibilities:

- GraphQL HTTP setup with just the Meteor WebApp, which is already available in Meteor. Forget about express and setting up an extra server. It just works.
- Subscriptions out-of-the-box (like DDPSubscriptionsLink, or using the new ClientStream core package)
- Automatically have the ability to import `.graphql` files. Because why wouldn't you want that when using Apollo? (I know, I know, slippery slope)

But what if people outgrow this? Well, they can use the 2 npm packages and do it all themselves. But if you're doing a hackathon and you want to use GraphQL in 5 seconds, you simply type `meteor add apollo` and BOOM, let's get started!

Long answer, but what do you think?

**Comment by jamiter** [comment]
Thanks for the quick reply and kind words @xavcz!

Let's focus on making this package compatible with 2.0 first and then move it to npm if possible.

*I removed my previous response because it was to much off-topic for this thread*

**Comment by lorensr** [comment]
ddp-apollo looks great, maybe we could deprecate in favor of it?

**Comment by zhe1ka** [comment]
any news about an integration apollo 2.0 with meteor?

**Comment by xavcz** [comment]
PR opened #114, really basic implementation that should do the job.

I'm no longer able to invest time in this package, we are actively looking for a new maintainer to join the team.

I hope everyone is having a good time, cheers 🎄

**Comment by you-fail-me** [comment]
when trying to create apollo server with meteor I'm getting:

**Comment by you-fail-me** [comment]
When trying to create an apollo server with meteor and apollo 2 I'm getting:
```
Error: Schema must be an instance of GraphQLSchema. Also ensure that there are not multiple versions of GraphQL installed in your node_modules directory
```
I've checked and I have only one graphql in my `node_modules`.
What could be the reason?
Stacktrace:
```
at invariant (/Users/.../node_modules/graphql/jsutils/invariant.js:18:11)<br> &nbsp; &nbsp;at Object.validate (/Users/.../node_modules/graphql/validation/validate.js:59:72)<br> &nbsp; &nbsp;at doRunQuery (/Users/.../node_modules/apollo-server-core/dist/runQuery.js:88:38)<br> &nbsp; &nbsp;at /Users/.../node_modules/apollo-server-core/dist/runQuery.js:22:54<br> &nbsp; &nbsp;at /Users/.../.meteor/packages/promise/.0.10.0.borizy.o9z8++os+web.browser+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
```
Server code:
```
import {makeExecutableSchema} from 'graphql-tools';

import {typeDefs} from './schema';
import {resolvers} from './resolvers';

import { createApolloServer } from 'meteor/apollo';

export const schema = makeExecutableSchema({
  typeDefs,
  resolvers
});

createApolloServer({
  schema
});
```
Apollo works ok if I try to attach it to an express route (`webapp.connectHandlers`) but not in the "meteor way". How can it be fixed? What is the reason?

**Comment by williamli** [comment]
I am looking to start to try Apollo with Meteor (+ React).
Should I start to work with this package or is https://github.com/Swydo/ddp-apollo better with 2.0 support? Is there anything that make this package a better choice compared to ddp-apollo?

**Comment by dobesv** [comment]
If you are already using meteor and just adding apollo on top of that, the ddp-apollo one might be nice since it'll use meteor's existing connection.

If you're not currently using meteor, probably better to keep things separated.

Why? It's better from an operational and performance perspective to deploy and maintain the apollo graphql server as a microservice rather than lump it in with a meteor server.  The two use different concurrency models (fibers in meteor vs promises in apollo) and combining them incurs some overhead (meteor attaches a new fiber to every promise).  They also have very different monitoring / management systems.

**Comment by you-fail-me** [comment]
Just my 2 cents on ddp-apollo. Why I was interested in this package is that because I wanna migrate a meteor app to express & graphql, and thus having a ddp-based solution would put me further from my goal to move away from meteor, ddp and stuff. While a solution like this, which uses express route would be way more suitable

**Comment by stolinski** [comment]
I agree with @you-fail-me which is why I haven't dove too much into ddp-apollo. My sweet spot would be something that connects Meteor's account system and that's pretty much it.

**Comment by hannwong** [comment]
@xavcz Assuming this package is the [Apollo for Metoer](https://atmospherejs.com/meteor/apollo), I'll invest time and people to this package (although I haven't even touched Meteor!). Can someone quickly walk me through how I should pick up maintainer capabilities/duties for this package? (I will walk as quickly as you do; I take apart software for a living, though no longer doing compiled codes.)
