### ISSUE TITLE
User Context For SSR

### ISSUE THREAD

**Issue by stolinski** [apollographql/meteor-integration#116]
Is this possible with this package? If not maybe we can explore a way to implement that feature. I was reading a bit about it with how fast-render managed it, but didn't get much further then that.

**Comment by lorensr** [comment]
Nope, I think the server would need to set an auth cookie, so that when the browser does a `GET /`, it sends along enough information for the server to look up the user. Would be nice, and would be applicable to Meteor in general (outside of Apollo), so most of it should probably be implemented in a separate package.

**Comment by smeijer** [comment]
I'm currently keeping a cookie on the client synced with the login token in local storage. This cookie will be sent as a header with the initial request. Which is being used to lookup the current user.

Maybe not so pretty, but it works.

**Comment by stolinski** [comment]
@smeijer 
Do you have any available examples of your implementation? I'd love to see how you're doing that.

**Comment by smeijer** [comment]
I needed to adjust my code a bit, as I'm using the `onTokenChange` hook from `meteor-apollo-accounts`. But this should work. If not, it for sure only need a little bit finetuning.

```js
// client, set and unset token in cookie

import { Accounts } from 'meteor/accounts-base';
import Cookie from 'js-cookie';

Accounts.onLogin(d => {
  const token = Accounts._storedLoginToken();
  const expires = Accounts._storedLoginTokenExpires();

  if (token) {
    const expireDate = new Date(expires);
    const today = new Date();
    const days = Math.floor((expireDate - today) / 1000 / 3600 / 24);

    Cookie.set('loginToken', token, { expires: days });
  } else {
    Cookie.remove('loginToken');
  }
});

Accounts.onLogout(d => {
  Cookie.remove('loginToken');
  window.location = '/';
});
```

``` js
// server, retrieve token from cookie

import { onPageLoad } from 'meteor/server-render';
import { getUserForContext } from 'meteor/apollo';

onPageLoad(async sink => {
  const { loginToken } = sink.getCookies();
  const { user } = await getUserForContext(loginToken);
});
```

---

When using `meteor-apollo-accounts`, like I am; you could use the `onTokenChange` instead of the `Accounts.onLogin` as written above:

```js
import { onTokenChange } from 'meteor-apollo-accounts';
import Cookie from 'js-cookie';

onTokenChange(({ userId, token, tokenExpires } = {}) => {
  if (token) {
    const expireDate = new Date(tokenExpires);
    const today = new Date();
    const days = Math.floor((expireDate - today) / 1000 / 3600 / 24);

    Cookie.set('loginToken', token, { expires: days });
  } else {
    Cookie.remove('loginToken');
  }
});
```

**Comment by stolinski** [comment]
Thanks!



SCOTT TOLINSKI
www.scotttolinski.com

**Comment by lorensr** [comment]
New issue for tracking documenting SSR: #126
